# Version of the Compose file format
# Version 3 is the most current and recommended one
version: "3"

# Top building block that defines
# All containers used for this service
services:

  # Container 1
  # https://hub.docker.com/_/mariadb
  db:
    # Image name (optinally version)
    # https://docs.docker.com/compose/compose-file/#image
    image: mariadb:latest
    container_name: mysql_loftschool
    # Define restart policy
    # https://docs.docker.com/compose/compose-file/#restart
    restart: unless-stopped
    # Volumes definition
    # Named volume, allows persisted data but without caring where locally it is stored
    # https://nickjanetakis.com/blog/docker-tip-28-named-volumes-vs-path-based-volumes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./:/var/www/html/
    # Add environment variables
    # https://docs.docker.com/compose/compose-file/#environment
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loftschool
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    # List of networks to join
    networks:
      - loftschool_net

  # Container 2
  # https://hub.docker.com/_/wordpress
  74-apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: php74_loftschool
    # List of dependencies
    depends_on:
      - db
    # Image name (optinally version)
    # https://docs.docker.com/compose/compose-file/#image
    # Feel free to add a version of WordPress
    # I.e. wordpress:5.2.0
    # image: wordpress
    # Define restart policy
    # https://docs.docker.com/compose/compose-file/#restart
    restart: unless-stopped
    container_name: wp_loftschool
    # Volumes definition
    # https://docs.docker.com/compose/compose-file/#volumes
    # Maps your local folder, to path in a container
    # Useful for file edits
    # I like to map only wp-content
    # We should not care about WP core files
    volumes: ["./:/var/www/html/"]
    # Add environment variables
    # https://docs.docker.com/compose/compose-file/#environment
    # Ports mapping
    ports:
      - 80:80
      - 443:443
    # List of networks to join
    networks:
      - loftschool_net

  # Container 3
  # https://hub.docker.com/_/adminer
  # This one is optional
  adminer:
    # List of dependencies
    depends_on:
      - db
    # Image name (optinally version)
    # https://docs.docker.com/compose/compose-file/#image
    image: adminer
    container_name: adminer_loftschool
    # Define restart policy
    # https://docs.docker.com/compose/compose-file/#restart
    restart: unless-stopped
    # Ports mapping
    ports:
      - 8080:8080
    # Add environment variables
    # https://docs.docker.com/compose/compose-file/#environment
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    # List of networks to join
    networks:
      - loftschool_net
      
# Top building block that defines
# All networks used for this service
networks:
  loftschool_net:

# Top building block that defines
# All volumes used for this service
volumes:
  db_data:
